const $=s=>document.querySelector(s), input=$("#videoFile"), video=$("#video"), canvas=$("#canvas"), ctx=canvas.getContext("2d"), status=$("#status"), bar=$("#bar"), convert=$("#convert"), done=$("#done"), preview=$("#preview");
let templateBuf,playerBuf,resultBlob,sourceURL;
const FRAME_COUNT=168,W=392,H=180;
$("#quality").oninput=e=>$("#qv").value=e.target.value+"%";
function cleanName(){let s=$("#saveName").value.trim().replace(/[\\/:*?"<>|]/g,"_");return s||"myvideo"}
async function bytes(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error(url+" 載入失敗");return r.arrayBuffer()}
Promise.all([bytes("templates/gb.melsave"),bytes("templates/gb mp4.melsave")]).then(v=>{templateBuf=v[0];playerBuf=v[1];status.textContent="✓ 原版模板已載入\n✓ gb.melsave：12 個根物件 × 14 個影格子物件 = 168 張材質\n等待影片。";if(video.duration)convert.disabled=false}).catch(e=>status.textContent="模板錯誤："+e.message);
function seek(t){return new Promise((ok,no)=>{const timer=setTimeout(()=>no(Error("影片定位逾時")),12000);video.addEventListener("seeked",()=>{clearTimeout(timer);ok()},{once:true});video.currentTime=Math.min(Math.max(t,0),Math.max(0,video.duration-.003))})}
function draw(){const sw=video.videoWidth,sh=video.videoHeight,tr=W/H,sr=sw/sh;let sx=0,sy=0,cw=sw,ch=sh;if(sr>tr){cw=sh*tr;sx=(sw-cw)/2}else{ch=sw/tr;sy=(sh-ch)/2}ctx.fillStyle="#000";ctx.fillRect(0,0,W,H);ctx.drawImage(video,sx,sy,cw,ch,0,0,W,H)}
function jpeg(q){return new Promise((ok,no)=>canvas.toBlob(async b=>b?ok(await b.arrayBuffer()):no(Error("JPEG 編碼失敗")),"image/jpeg",q))}
input.onchange=()=>{const f=input.files[0];if(!f)return;if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL=URL.createObjectURL(f);video.src=sourceURL;$("#fileName").textContent=f.name;$("#fileInfo").textContent=(f.size/1048576).toFixed(2)+" MB";done.hidden=true;video.onloadedmetadata=async()=>{status.textContent=`影片 ${video.duration.toFixed(2)} 秒\n將平均擷取 168 幀。`;convert.disabled=!templateBuf;try{await seek(0);draw();preview.src=canvas.toDataURL("image/jpeg",.8);preview.style.display="block"}catch{}}};
async function patchVideo(frames){const z=await JSZip.loadAsync(templateBuf);for(let i=1;i<=FRAME_COUNT;i++){if(!z.file(String(i)))throw Error("原版模板缺少 AssetId "+i);z.file(String(i),frames[i-1],{binary:true,compression:"DEFLATE"})}return z.generateAsync({type:"uint8array",compression:"DEFLATE",compressionOptions:{level:6}})}
async function patchPlayer(name){const z=await JSZip.loadAsync(playerBuf),df=z.file("Data");if(!df)throw Error("播放器缺少 Data");const obj=JSON.parse(await df.async("string"));let hits=0;for(const c of obj.saveObjectContainers||[]){const so=c.saveObjects||{};for(const m of so.saveMetaDatas||[]){if(m.key==="lua_chip_source"&&typeof m.stringValue==="string"&&m.stringValue.includes('spawn.createSave("gb",3,3)')){m.stringValue=m.stringValue.replace('spawn.createSave("gb",3,3)',`spawn.createSave(${JSON.stringify(name)},3,3)`);hits++}}}if(hits!==1)throw Error("播放器名稱綁定數量異常："+hits);z.file("Data",JSON.stringify(obj));return z.generateAsync({type:"uint8array",compression:"DEFLATE",compressionOptions:{level:6}})}
async function verify(videoBytes,playerBytes,name){const vz=await JSZip.loadAsync(videoBytes);const names=Object.keys(vz.files);for(let i=1;i<=168;i++)if(!vz.file(String(i)))throw Error("驗證失敗：缺影格 "+i);const data=JSON.parse(await vz.file("Data").async("string"));let roots=data.saveObjectContainers||[],children=0,assets=[];for(const c of roots){children+=(c.saveObjectChildren||[]).length;for(const ch of c.saveObjectChildren||[]){const a=ch?.humanData?.[0]?.texture?.AssetId;if(a)assets.push(a)}}if(roots.length!==12||children!==168)throw Error(`驗證失敗：物件結構 ${roots.length}× / ${children}`);for(let i=1;i<=168;i++)if(!assets.includes(String(i)))throw Error("驗證失敗：Data 未引用 AssetId "+i);
 const pz=await JSZip.loadAsync(playerBytes),po=JSON.parse(await pz.file("Data").async("string"));let src="";for(const c of po.saveObjectContainers||[])for(const m of c.saveObjects?.saveMetaDatas||[])if(m.key==="lua_chip_source")src+=m.stringValue||"";if(!src.includes(`spawn.createSave(${JSON.stringify(name)},3,3)`))throw Error("驗證失敗：播放器沒有綁定新名稱");return `✓ 影片存檔：12 個根物件 / 168 個影格子物件\n✓ AssetId 1～168 全部存在並被 Data 引用\n✓ 播放器 spawn.createSave 綁定：${name}\n✓ 兩個 .melsave 均可重新解包`}
convert.onclick=async()=>{if(!video.duration||!templateBuf||!playerBuf)return;convert.disabled=true;done.hidden=true;bar.style.width="0";try{const q=+$("#quality").value/100,frames=[];for(let i=0;i<168;i++){status.textContent=`擷取 ${i+1}/168`;await seek(video.duration*i/168);draw();frames.push(await jpeg(q));bar.style.width=(i/168*78)+"%";if(i%4===0)await new Promise(r=>setTimeout(r,0))}const name=cleanName();status.textContent="建立原版結構存檔…";const vb=await patchVideo(frames);bar.style.width="84%";const pb=await patchPlayer(name);bar.style.width="90%";status.textContent="重新解包並驗證…";const report=await verify(vb,pb,name);bar.style.width="96%";const out=new JSZip();out.file(`${name}.melsave`,vb,{binary:true,compression:"STORE"});out.file(`${name} mp4.melsave`,pb,{binary:true,compression:"STORE"});out.file("驗證結果.txt",report+"\n\n注意：這是檔案結構自我驗證；瀏覽器無法直接啟動 Melon Playground 做遊戲內執行測試。",{compression:"DEFLATE"});resultBlob=await out.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}});bar.style.width="100%";status.textContent=report+"\n✓ 轉換完成";done.hidden=false}catch(e){console.error(e);status.textContent="✗ "+e.message}finally{convert.disabled=false}};
$("#download").onclick=()=>{if(!resultBlob)return;const a=document.createElement("a");a.href=URL.createObjectURL(resultBlob);a.download=cleanName()+"-Melon播放器.zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
